### ISSUE TITLE
Make Contract fields editable (after clicking edit)

### ISSUE THREAD

**Issue by laradg** [laradg/magno-intranet#21]
On tab Kandidaat:
Opzegtermijn, Werkbare uren, Betaaltermijn, Begindatum, Einddatum, Opmerkingen

On tab Klant:
Inkooptarief, Verkooptarief, Marge, Per, Opzegtermijn, Werkbare uren, Betaaltermijn, Begindatum, Einddatum, Opmerkingen

**Comment by davedx** [comment]
Fixed in git
