### ISSUE TITLE
Remember Dashboard filter choice 

### ISSUE THREAD

**Issue by laradg** [laradg/magno-intranet#34]
Remember whether table was filtered on alphabetically descending, alphabetically ascending, date desc or date ascending, so that the same view is opened next time user logs in to Intranet.

**Comment by laradg** [comment]
This works perfectly when I press the "back" button from the contracts module, but it does not remember my choice when I close and reopen the Dashboard, or when I go to the Kalender and back - even though the session ID hasn't changed.
I assume some code needs to be added to the intranet dashboard solution?

**Comment by davedx** [comment]
Hmm that's strange, it worked for me when I refreshed the whole page which should be a full reload. It could definitely be a bug in how contracts loads/saves the settings though. I'll have a look at it tonight.

**Comment by davedx** [comment]
Fixed by Lara 👍
