### ISSUE TITLE
Clear selection button in Search

### ISSUE THREAD

**Issue by laradg** [laradg/magno-intranet#38]
![image](https://user-images.githubusercontent.com/24442624/54194359-5dd08d80-44bc-11e9-94b7-d7b50552e676.png)

Would it be possible to add a "x" button to clear the selection in the text box if a value is filled in, similar to what you have in Microsoft search bars? See example image ("x" is a very dark grey colour)

**Comment by davedx** [comment]
Sure!

**Comment by laradg** [comment]
:)
